name: Publish to WinGet

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: read-all

    steps:
      - name: Extract version from tag
        id: extract_version
        run: |
          version=$(echo "${{ github.event.release.tag_name }}" | grep -oP "(?<=v)[\d.]+")
          echo "version=$version" >> $GITHUB_OUTPUT
      - uses: vedantmgoyal9/winget-releaser@a2ac6c7691dd063a6f6e782fdd11090f5ab45525
        with:
          identifier: Microsoft.OpenSSH.Preview
          version: ${{ steps.extract_version.outputs.version }}
          token: ${{ secrets.WINGET_TOKEN }}
          fork-user: pwshBot
